Repository projectsyn/commodore, pull requests merged in 2021-08, with the labels that each got.

#351 Fix `render_target` to ensure instantiated components always compile
  commodore/cluster.py
  tests/test_render_inventory.py
Labels: bug

#354 Implement option to specify target alias for `commodore component compile`
  commodore/cli.py
  commodore/component/compile.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_component_compile.py
Labels: enhancement

#353 Fix postprocessing filter lookup
  commodore/postprocess/__init__.py
  commodore/postprocess/builtin_filters.py
  commodore/postprocess/jsonnet.py
Labels: bug

#357 Fix postprocessing for instantiated components
  commodore/postprocess/__init__.py
  commodore/postprocess/builtin_filters.py
  commodore/postprocess/jsonnet.py
  docs/modules/ROOT/pages/reference/architecture.adoc
  tests/test_postprocess.py
Labels: bug

#356 Refactor postprocessing tests
  tests/test_postprocess.py
Labels: change

#359 Provide dynamic facts in Reclass hierarchy
  Makefile
  commodore/cluster.py
  docs/modules/ROOT/pages/.vale.ini
  docs/modules/ROOT/pages/reference/architecture.adoc
  docs/modules/ROOT/pages/reference/parameters.adoc
  tests/test_cluster.py
  tests/test_target.py
Labels: enhancement

#361 Set explicit encoding to fix pylint warnings
  commodore/component/__init__.py
  commodore/component/compile.py
  commodore/config.py
  commodore/dependency_mgmt.py
  commodore/helpers.py
  commodore/postprocess/jsonnet.py
Labels: change

#360 Exclude jsonnet files from indent linter
  commodore/component-template/{{ cookiecutter.slug }}/.editorconfig
Labels: change

#363 Make yamllint exludes work on both BSD and GNU
  commodore/component-template/{{ cookiecutter.slug }}/.yamllint.yml
  commodore/component-template/{{ cookiecutter.slug }}/Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: change
