Repository projectsyn/commodore, pull requests merged in 2021-07, with the labels that each got.

#341 Always fetch Kapitan dependencies
  commodore/helpers.py
Labels: enhancement

#251 Integration test for catalog compilation
  .github/workflows/test.yml
  Makefile
  commodore/config.py
  tests/test_catalog_compile.py
  tox.ini
Labels: enhancement

#346 Use fixed globalGitRepoRevision for integration test
  tests/test_catalog_compile.py
Labels: bug

#345 Fix component template
  commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/test.yaml
  commodore/component-template/{{ cookiecutter.slug }}/class/{{ cookiecutter.slug }}.yml
  tests/test_component_template.py
Labels: bug

#349 Add local dependencies search path in commodore test compile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile
Labels: change

#348 Correctly postprocess aliased components
  commodore/component/compile.py
  commodore/postprocess/__init__.py
  commodore/postprocess/builtin_filters.py
  commodore/postprocess/jsonnet.py
  tests/test_postprocess.py
Labels: bug
