Repository projectsyn/commodore, pull requests merged in 2021-12, with the labels that each got.

#391 Remove support for deprecated parameter `commodore.jsonnet_libs`
  commodore/compile.py
  commodore/dependency_mgmt.py
  docs/modules/ROOT/pages/reference/deprecation-notices.adoc
Labels: breaking

#390 Add deprecation notice for component specifications without explicit version
  commodore/dependency_mgmt.py
  docs/modules/ROOT/pages/reference/deprecation-notices.adoc
  tests/test_catalog_compile.py
  tests/test_dependency_mgmt.py
Labels: change

#393 Add trailing newline when writing a `jsonnetfile.json`
  commodore/component/__init__.py
  commodore/dependency_mgmt.py
  tests/test_component_compile.py
  tests/test_dependency_mgmt.py
Labels: bug

#392 Add support for tenant repo in `commodore inventory components`
  commodore/cli.py
  commodore/inventory/parameters.py
  commodore/inventory/render.py
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_inventory_parameters.py
  tests/test_inventory_render.py
Labels: enhancement

#394 Update Python dependencies
  poetry.lock
Labels: dependency

#395 Fix command `inventory components` for inventories which use `${_instance}`
  commodore/inventory/parameters.py
  tests/test_inventory_parameters.py
Labels: bug

#396 Use absolute Docker Image URLs
  Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: bug
