Repository projectsyn/commodore, pull requests merged in 2021-06, with the labels that each got.

#322 Install type dependencies for mypy linting
  tox.ini
Labels: ignore

#324 Bulk update Python dependencies
  poetry.lock
Labels: dependency

#325 Bump Kapitan for ArgoCD to v0.29.5
  tools/Dockerfile.kapitan
Labels: dependency

#327 Pin Kapitan to v0.29.4 to avoid regressions in v0.29.5
  poetry.lock
  pyproject.toml
Labels: dependency

#328 Fix releases to show "x commits to master since this release"
  .github/workflows/push.yml
Labels: ignore

#329 Show number of commits to master since the release in component releases
  commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/release.yaml
Labels: bug

#331 Implement simple regression tests for Kapitan's bundled Reclass
  tests/test_kapitan_reclass.py
  tests/testdata/inventory_apps/classes/test.yml
  tests/testdata/inventory_apps/classes/test/params.yml
  tests/testdata/inventory_apps/classes/test/specific.yml
  tests/testdata/inventory_apps/targets/test.yml
  tests/testdata/inventory_relative_refs/classes/test.yml
  tests/testdata/inventory_relative_refs/classes/test/common.yml
  tests/testdata/inventory_relative_refs/classes/test/specific.yml
  tests/testdata/inventory_relative_refs/targets/test.yml
  tests/testdata/inventory_yml_yaml/classes/a.yml
  tests/testdata/inventory_yml_yaml/classes/b.yaml
  tests/testdata/inventory_yml_yaml/targets/test.yml
Labels: enhancement

#332 New style for documentation preview
  Makefile
  docs/modules/ROOT/assets/images/projectsyn.svg
  docs/modules/ROOT/assets/images/syn.png
  docs/modules/ROOT/assets/images/vshn.png
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/reference/cli.adoc
Labels: documentation, enhancement

#336 Use current working directory when searching for .env
  commodore/cli.py
Labels: bug

#337 Create a pypi package and publish it
  .dockerignore
  .github/workflows/publish-pypi.yml
  Dockerfile
  Makefile
  README.md
  commodore/__init__.py
  commodore/cli.py
  commodore/copy_helm_bindings.py
  pyproject.toml
Labels: enhancement

#335 Add ModuleSync support in component template
  commodore/component-template/{{ cookiecutter.slug }}/.sync.yml
  commodore/component-template/{{ cookiecutter.slug }}/Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
  commodore/component-template/{{ cookiecutter.slug }}/tests/defaults.yml
Labels: enhancement
