Repository projectsyn/commodore, pull requests merged in 2021-05, with the labels that each got.

#312 Fix prereleases not being applied when using release candidates
  .github/workflows/push.yml
  commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/release.yaml
Labels: bug

#316 Implement support for deprecating components
  commodore/compile.py
  commodore/component-template/{{ cookiecutter.slug }}/class/defaults.yml
  commodore/config.py
  docs/modules/ROOT/pages/reference/component-deprecation.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  tests/test_config.py
Labels: enhancement

#318 Fix typo in examples
  docs/modules/ROOT/pages/reference/component-deprecation.adoc
Labels: ignore
