Repository projectsyn/commodore, pull requests merged in 2021-11, with the labels that each got.

#358 Upgrade to Kapitan v0.30
  .github/workflows/test.yml
  Dockerfile
  Makefile
  README.md
  commodore/catalog.py
  commodore/cli.py
  commodore/config.py
  commodore/copy_helm_bindings.py
  commodore/git.py
  commodore/helpers.py
  commodore/k8sobject.py
  docs/modules/ROOT/pages/explanation/dependencies.adoc
  docs/modules/ROOT/pages/explanation/local-mode.adoc
  docs/modules/ROOT/pages/explanation/migrate-kapitan-0.29-0.30.adoc
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/partials/nav-explanation.adoc
  poetry.lock
  pyproject.toml
  tests/test_catalog_compile.py
  tests/test_component_compile.py
  tests/test_helpers.py
  tests/test_k8sobject.py
  tools/Dockerfile.build_kapitan_helm_binding
  tools/build_kapitan_helm_binding.sh
  tools/tools.py
  tox.mk
Labels: dependency, breaking

#376 Fix and improve PyPI build
  .github/workflows/publish-pypi.yml
  .github/workflows/test.yml
  Makefile
  README.md
  pyproject.toml
Labels: change

#378 Correctly inject Git version in CI package builds
  Makefile
Labels: bug

#379 Allow ARM Docker build
  .dockerignore
  Dockerfile
  tools/install-jb.sh
Labels: enhancement

#380 Fix typos in dynamic facts example
  docs/modules/ROOT/pages/reference/parameters.adoc
Labels: documentation

#381 Fix unit tests
  .github/workflows/test.yml
  tests/test_component_compile.py
  tests/test_component_template.py
  tests/test_postprocess.py
Labels: ignore

#382 Sync component template from modulesync-control
  commodore/component-template/{{ cookiecutter.slug }}/.github/PULL_REQUEST_TEMPLATE.md
  commodore/component-template/{{ cookiecutter.slug }}/Makefile
Labels: change

#383 Add CLI command to extract component versions and URLs
  .gitignore
  commodore/cli.py
  commodore/inventory/__init__.py
  commodore/inventory/parameters.py
  commodore/inventory/render.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_cli.py
  tests/test_inventory_parameters.py
  tests/test_inventory_render.py
Labels: enhancement

#384 Fix unreliable path type conversion in `commodore inventory components`
  commodore/cli.py
Labels: bug

#387 Disable Renovate dependency dashboard
  commodore/component-template/{{ cookiecutter.slug }}/renovate.json
  renovate.json
Labels: change
