Repository projectsyn/commodore, pull requests merged in 2021-04, with the labels that each got.

#309 Add changelog generator to workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/changelog-configuration.json
  .github/workflows/push.yml
  CHANGELOG.md
  README.md
  commodore/component-template/{{ cookiecutter.slug }}/.github/PULL_REQUEST_TEMPLATE.md
  commodore/component-template/{{ cookiecutter.slug }}/.github/changelog-configuration.json
  commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/release.yaml
  commodore/component-template/{{ cookiecutter.slug }}/CHANGELOG.md
  commodore/component-template/{{ cookiecutter.slug }}/renovate.json
  docs/modules/ROOT/pages/reference/deprecation-notices.adoc
  renovate.json
  tests/test_component_template.py
Labels: change

#310 Fix whitespace error from yamllint in component template
  commodore/component-template/{{ cookiecutter.slug }}/.github/workflows/release.yaml
Labels: bug

#311 Introduce inventory parameters for cluster and tenant display names
  commodore/cluster.py
  commodore/compile.py
  docs/modules/ROOT/pages/reference/parameters.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  tests/test_cluster.py
  tests/test_target.py
Labels: enhancement
