Repository projectsyn/commodore, pull requests merged in 2022-10, with the labels that each got.

#646 Improve support for `kustomize` in Commodore
  commodore/__init__.py
  commodore/cluster.py
  commodore/component/compile.py
  commodore/lib/commodore.libjsonnet
  commodore/scripts/run-kustomize
  docs/modules/ROOT/pages/reference/commodore-libjsonnet.adoc
  docs/modules/ROOT/pages/reference/parameters.adoc
  pyproject.toml
  tests/test_component_compile.py
  tests/test_target.py
Labels: enhancement

#656 Improve local mode documentation
  docs/modules/ROOT/pages/explanation/local-mode.adoc
  docs/modules/ROOT/pages/how-to/local-mode-component.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: documentation

#660 Avoid crash in `inventory lint` when top-level `parameters` is not an object
  commodore/inventory/lint.py
  tests/test_inventory_lint_components.py
Labels: bug

#665 Implement ignore patterns for `inventory lint`
  commodore/cli.py
  commodore/inventory/lint.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_inventory_lint_components.py
Labels: enhancement

#672 Refactor `cli.py` into a package
  commodore/cli.py
  commodore/cli/__init__.py
  commodore/cli/catalog.py
  commodore/cli/component.py
  commodore/cli/inventory.py
  commodore/cli/oidc.py
  commodore/cli/options.py
  commodore/cli/package.py
  tests/test_cli_catalog.py
  tests/test_cli_component.py
  tests/test_cli_functions.py
  tests/test_cli_inventory.py
  tests/test_cli_oidc.py
  tests/test_cli_package.py
Labels: internal

#673 Add support for selective dependency syncing
  commodore/cli/component.py
  commodore/cli/options.py
  commodore/cli/package.py
  commodore/dependency_syncer.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_cli_component.py
  tests/test_cli_package.py
  tests/test_dependency_sync.py
Labels: enhancement

#671 Improve catalog listing UX
  .editorconfig
  Makefile
  commodore/catalog.py
  commodore/cli/catalog.py
  commodore/helpers.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_catalog.py
  tests/test_cli_catalog.py
  tests/testdata/catalog_list/id_multi
  tests/testdata/catalog_list/id_single
  tests/testdata/catalog_list/json_multi
  tests/testdata/catalog_list/pretty_multi
  tests/testdata/catalog_list/yaml_multi
  tests/testdata/catalog_list/yml_multi
Labels: enhancement

#670 Add Python 3.11 as supported version
  .github/workflows/build-virtualenv-caches.yml
  .github/workflows/test.yml
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
  poetry.lock
  pyproject.toml
  tox.ini
  tox.mk
Labels: enhancement

#666 Make non-dictionary key `parameters` a linting error
  commodore/inventory/lint.py
  commodore/inventory/lint_dependency_specification.py
  tests/test_inventory_lint_components.py
Labels: bug

#674 Update supported Python versions in README.md
  README.md
Labels: ignore

#677 Label Renovate lockFileMaintenance PRs with `ignore`
  renovate.json
Labels: ignore
