Repository projectsyn/commodore, pull requests merged in 2022-11, with the labels that each got.

#684 Add missing `Optional` to function arguments with default value `None`
  commodore/dependency_mgmt/jsonnet_bundler.py
  commodore/helpers.py
  commodore/inventory/__init__.py
  commodore/inventory/parameters.py
Labels: ignore

#686 Fix mounting of GPG agent to Commodore docker container on Linux
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
Labels: documentation

#687 Skip GitHub actions which need additional secrets on PRs from forks
  .github/workflows/coverage.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/test.yml
Labels: ignore

#689 Fix list indentation if using post-process filters
  commodore/catalog.py
  commodore/cli/catalog.py
  commodore/config.py
  commodore/helpers.py
  docs/modules/ROOT/pages/reference/cli.adoc
  tests/test_catalog.py
  tests/test_helpers.py
Labels: bug

#685 Add new command line flag `--force` for `catalog compile`
  commodore/cli/catalog.py
  commodore/compile.py
  commodore/component/__init__.py
  commodore/dependency_mgmt/__init__.py
  commodore/gitrepo/__init__.py
  commodore/gitrepo/diff.py
  commodore/package/__init__.py
  docs/modules/ROOT/pages/reference/cli.adoc
  tests/test_compile.py
  tests/test_component.py
  tests/test_dependency_mgmt.py
  tests/test_gitrepo.py
  tests/test_gitrepo_diff.py
  tests/test_package.py
Labels: enhancement

#694 Vendor `kube-libsonnet`
  .editorconfig
  commodore/dependency_mgmt/jsonnet_bundler.py
  commodore/lib/kube-libsonnet/kube.libsonnet
  commodore/lib/kube.libjsonnet
  commodore/lib/kube.libsonnet
  docs/modules/ROOT/pages/reference/kube-libjsonnet.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  pyproject.toml
  tests/test_component_compile.py
  tests/test_dependency_mgmt_jsonnet_bundler.py
  tests/test_postprocess.py
Labels: change

#696 Remove Python 3.9.7 from test matrix
  .github/workflows/build-virtualenv-caches.yml
  .github/workflows/test.yml
Labels: ignore
