Repository projectsyn/commodore, pull requests merged in 2022-01, with the labels that each got.

#399 Improve error messages for duplicate component aliases
  commodore/dependency_mgmt.py
  tests/test_dependency_mgmt.py
Labels: change

#398 Properly handle 403 replies from Lieutenant
  commodore/catalog.py
  commodore/helpers.py
  poetry.lock
  pyproject.toml
  tests/test_helpers.py
  tox.ini
Labels: bug

#397 Update component template to ensure files are generated with the correct GID
  Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: bug

#400 Add new command `inventory lint`
  commodore/cli.py
  commodore/inventory/lint_components.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_cli.py
  tests/test_inventory_lint_components.py
Labels: enhancement

#401 Update Kapitan to 0.30.0rc1
  .github/workflows/test.yml
  commodore/component/__init__.py
  poetry.lock
  pyproject.toml
Labels: dependency

#402 Update Docker base image to `python:3.9.10-slim-bullseye`
  Dockerfile
Labels: dependency

#404 Fix `/usr/lib/libnss_wrapper.so` not found error in Docker image
  .github/workflows/test.yml
  tools/entrypoint.sh
Labels: bug

#405 Cache virtualenv in GitHub action which publishes the package on PyPI
  .github/workflows/publish-pypi.yml
Labels: ignore

#406 Add GitHub action to build virtualenv caches on master branch
  .github/workflows/build-virtualenv-caches.yml
  .github/workflows/test.yml
  tox.ini
  tox.mk
Labels: ignore
