Repository projectsyn/commodore, pull requests merged in 2022-08, with the labels that each got.

#572 Add new command `package sync`
  commodore/cli.py
  commodore/config.py
  commodore/package/__init__.py
  commodore/package/sync.py
  commodore/package/template.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  poetry.lock
  pyproject.toml
  tests/test_cli.py
  tests/test_cli_functions.py
  tests/test_package_sync.py
  tests/testdata/github/projectsyn-package-foo-response-pr.json
  tests/testdata/github/projectsyn-package-foo-response-pulls.json
  tests/testdata/github/projectsyn-package-foo-response.json
Labels: enhancement

#576 Use each repo's default branch as the PR base branch for `package sync`
  commodore/cli.py
  commodore/package/sync.py
  docs/modules/ROOT/pages/reference/commands.adoc
Labels: ignore

#575 Pass `SSH_AUTH_SOCK` environment variable to tox-based tests
  tox.ini
Labels: ignore

#577 Remove development dependency `autopep8`
  poetry.lock
  pyproject.toml
  tools/tools.py
Labels: dependency

#578 Fix console output for `package sync`
  commodore/package/sync.py
  tests/test_package_sync.py
Labels: bug

#580 Add a note about required dev packages for building Commodore dependencies
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
Labels: documentation

#581 Update suggested Commodore-in-Docker helpers
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
Labels: documentation

#583 Fix config package path in package tutorial
  docs/modules/ROOT/pages/tutorial/package.adoc
Labels: documentation

#584 Ensure that there's no chance that test cases compete for ports
  commodore/login.py
  tests/test_login.py
Labels: ignore

#582 Deprecate parameter `--repo-directory` for component compile
  commodore/cli.py
  commodore/component/__init__.py
  commodore/component/compile.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  docs/modules/ROOT/pages/reference/deprecation-notices.adoc
  tests/test_cli_functions.py
  tests/test_component.py
  tests/test_component_compile.py
Labels: change

#586 Add logic in component template `Makefile.vars.mk` to handle Git worktree checkouts
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: bug

#585 Fix `Component.render_jsonnetfile_json()` when no repo detected
  commodore/component/__init__.py
  tests/test_component.py
Labels: ignore

#588 Hard-code component name in component template `Makefile.vars.mk`
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: change

#589 Update Commodore-in-Docker to support GPG-signing commits on Linux
  Dockerfile
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
Labels: change

#592 Fix dependency spec linting for dependencies in subpaths
  commodore/inventory/lint_dependency_specification.py
  tests/test_inventory_lint_components.py
Labels: bug

#594 Add new command `component update`
  commodore/cli.py
  commodore/component/template.py
  commodore/dependency_templater.py
  commodore/package/template.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_component_compile.py
  tests/test_component_template.py
  tests/test_package_compile.py
  tests/test_package_sync.py
  tests/test_postprocess.py
Labels: enhancement

#598 Correctly pass Git author name and email in `catalog compile`
  commodore/compile.py
Labels: bug

#599 Add option to create additional test cases for `component new`
  commodore/cli.py
  commodore/component/template.py
  commodore/dependency_templater.py
  commodore/package/template.py
  docs/modules/ROOT/pages/reference/cli.adoc
  tests/test_component_template.py
Labels: enhancement

#602 Correctly pass Git author name and email to dependency repos
  commodore/config.py
  commodore/multi_dependency.py
Labels: bug

#603 Correctly propagate Git author information when managing worktrees
  commodore/component/__init__.py
  commodore/gitrepo.py
  commodore/multi_dependency.py
  commodore/package/__init__.py
  tests/conftest.py
Labels: bug

#601 Add warning regarding "class not found" messages when using packages
  docs/modules/ROOT/pages/tutorial/package.adoc
Labels: documentation

#604 Handle `KeyError` when reading Git user from config
  commodore/gitrepo.py
Labels: bug

#605 Fix GitRepo initialization for dependencies without backing MultiDependency
  commodore/component/__init__.py
  commodore/package/__init__.py
  tests/test_component.py
Labels: bug

#600 Add support for adding and removing test cases to `component update`
  commodore/cli.py
  commodore/dependency_templater.py
  commodore/package/template.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_component_template.py
Labels: enhancement

#606 Fix entrypoint script in case the `.ssh` folder already exists
  tools/entrypoint.sh
Labels: bug

#607 Add command `component sync`
  commodore/cli.py
  commodore/component/__init__.py
  commodore/dependency_syncer.py
  commodore/dependency_templater.py
  commodore/package/__init__.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_cli_functions.py
  tests/test_component.py
  tests/test_dependency_sync.py
Labels: enhancement

#609 Read cookiecutter args from `.cruft.json` in Templater
  commodore/dependency_templater.py
  tests/test_component_template.py
Labels: enhancement

#610 Add fallback logic for component template `add_pp` and `add_lib` cookiecutter args
  commodore/component/template.py
  commodore/dependency_templater.py
  tests/test_component_template.py
Labels: enhancement

#611 Explicitly handle Cruft errors and merge conflicts in `Templater.update()`
  commodore/dependency_templater.py
  commodore/gitrepo.py
  tests/test_component_template.py
  tests/test_gitrepo.py
Labels: enhancement

#614 Add fallback to extract copyright info from modulesync config
  commodore/component/template.py
  commodore/dependency_templater.py
  tests/test_component_template.py
Labels: enhancement

#616 Add option to skip committing changes for `component update`/`package update`
  commodore/cli.py
  commodore/dependency_syncer.py
  commodore/dependency_templater.py
  docs/modules/ROOT/pages/reference/cli.adoc
  tests/test_component_template.py
  tests/test_dependency_sync.py
Labels: enhancement
