Repository projectsyn/commodore, pull requests merged in 2022-02, with the labels that each got.

#409 Address black format linting errors
  poetry.lock
  pyproject.toml
  tests/test_catalog_compile.py
Labels: ignore

#408 Update the component template docs preview command
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: enhancement

#410 Bump `vshn/antora-preview` image in component template to 3.0.1.0
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: ignore

#411 Move component instantiation advertisement to `_metadata.multi_instance`
  commodore/config.py
  docs/modules/ROOT/pages/reference/architecture.adoc
  docs/modules/ROOT/pages/reference/deprecation-notices.adoc
  tests/test_config.py
Labels: change

#412 Add virtualenv caching for linting GitHub actions and rebuild base cache weekly
  .github/workflows/build-virtualenv-caches.yml
  .github/workflows/test.yml
  tox.mk
Labels: ignore

#413 Update link to Commodore site
  commodore/component-template/{{ cookiecutter.slug }}/README.md
Labels: documentation

#407 Use the same Git checkout logic everywhere
  commodore/catalog.py
  commodore/compile.py
  commodore/component/__init__.py
  commodore/component/template.py
  commodore/config.py
  commodore/git.py
  commodore/gitrepo.py
  tests/bench_component.py
  tests/bench_gitrepo.py
  tests/mock_gitrepo.py
  tests/test_catalog.py
  tests/test_catalog_compile.py
  tests/test_compile.py
  tests/test_component.py
  tests/test_dependency_mgmt.py
  tests/test_git.py
  tests/test_gitrepo.py
  tox.ini
Labels: change

#418 Update default `kube-libsonnet` version to v1.19.0
  commodore/dependency_mgmt.py
  tests/test_dependency_mgmt.py
Labels: dependency
