Repository projectsyn/commodore, pull requests merged in 2022-03, with the labels that each got.

#421 Fix docker image if running on non-`x86` architectures
  tools/entrypoint.sh
Labels: bug

#422 Fix `GitRepo.push()` when pushing to empty remote repository
  commodore/gitrepo.py
  tests/test_gitrepo.py
Labels: bug

#423 Updated antora-preview image
  Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: documentation

#429 Fix typo in `testenv_py3.10` make target
  tox.mk
Labels: ignore

#426 Add OIDC integration for Lieutenant communication
  commodore/cli.py
  commodore/config.py
  commodore/login.py
  commodore/tokencache.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  poetry.lock
  pyproject.toml
  tests/test_cli.py
  tests/test_config.py
  tests/test_login.py
  tests/test_tokencache.py
  tox.ini
Labels: enhancement

#431 Auto-login when trying to authenticate without token
  commodore/cli.py
  commodore/config.py
  commodore/login.py
  tests/test_config.py
Labels: enhancement

#432 Update component template to support Podman out of the box
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: enhancement

#435 Auto discover OIDC configuration if not set
  commodore/login.py
  tests/test_login.py
Labels: enhancement

#436 Add frequently used functions to `commodore.libjsonnet`
  commodore/lib/commodore.libjsonnet
  commodore/postprocess/jsonnet.py
  docs/modules/ROOT/pages/reference/commodore-libjsonnet.adoc
  docs/modules/ROOT/partials/nav-reference.adoc
  tests/jsonnet/envList.json
  tests/jsonnet/envList.jsonnet
  tests/jsonnet/fixupDir.json
  tests/jsonnet/fixupDir.jsonnet
  tests/jsonnet/generateResources.json
  tests/jsonnet/generateResources.jsonnet
  tests/jsonnet/getValueOrDefault.json
  tests/jsonnet/getValueOrDefault.jsonnet
  tests/jsonnet/inventory.json
  tests/jsonnet/inventory.jsonnet
  tests/jsonnet/inventory.yaml
  tests/jsonnet/list_dir.json
  tests/jsonnet/list_dir.jsonnet
  tests/jsonnet/makeMergeable.json
  tests/jsonnet/makeMergeable.jsonnet
  tests/jsonnet/namespaced.json
  tests/jsonnet/namespaced.jsonnet
  tests/jsonnet/noProxyVars.json
  tests/jsonnet/noProxyVars.jsonnet
  tests/jsonnet/noProxyVars.yaml
  tests/jsonnet/proxyVars.json
  tests/jsonnet/proxyVars.jsonnet
  tests/jsonnet/proxyVars.yaml
  tests/jsonnet/renderArray.json
  tests/jsonnet/renderArray.jsonnet
  tests/jsonnet/yaml_load.json
  tests/jsonnet/yaml_load.jsonnet
  tests/test_commodore_libjsonnet.py
Labels: enhancement

#437 component-template: Split `COMMODORE_CMD` and `COMPILE_CMD` in Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
  tests/test_component_template.py
Labels: change
