Repository projectsyn/commodore, pull requests merged in 2022-06, with the labels that each got.

#528 Fix component template `.gitignore` entries
  commodore/component-template/{{ cookiecutter.slug }}/.gitignore
Labels: bug

#529 Add link to rendered documentation in component template README
  commodore/component-template/{{ cookiecutter.slug }}/.sync.yml
  commodore/component-template/{{ cookiecutter.slug }}/README.md
  tests/test_component_template.py
Labels: enhancement

#531 Fix bug in catalog update logic for initial compilation of a cluster
  commodore/catalog.py
Labels: bug

#533 Add `/dependencies` to component template `.gitignore`
  commodore/component-template/{{ cookiecutter.slug }}/.gitignore
Labels: bug

#536 Add short tutorial on how to write and use commodore packages
  docs/modules/ROOT/pages/tutorial/package.adoc
  docs/modules/ROOT/partials/nav-tutorials.adoc
Labels: documentation
