Repository projectsyn/commodore, pull requests merged in 2022-07, with the labels that each got.

#544 component-template: Add `lint_kubent` make targets to check for deprecated API versions
  commodore/component-template/{{ cookiecutter.slug }}/Makefile
  commodore/component-template/{{ cookiecutter.slug }}/Makefile.vars.mk
Labels: enhancement

#546 Clone config packages to `dependencies/pkg.{package-name}`
  commodore/dependency_mgmt/__init__.py
  commodore/package/__init__.py
  commodore/package/compile.py
  docs/modules/ROOT/pages/reference/concepts.adoc
  tests/test_dependency_mgmt.py
Labels: change

#547 Add support for dependencies in repository subpaths
  commodore/cli.py
  commodore/component/__init__.py
  commodore/component/compile.py
  commodore/dependency_mgmt/__init__.py
  commodore/dependency_mgmt/jsonnet_bundler.py
  commodore/dependency_mgmt/version_parsing.py
  commodore/package/__init__.py
  docs/modules/ROOT/pages/reference/architecture.adoc
  docs/modules/ROOT/pages/reference/concepts.adoc
  tests/test_component_compile.py
  tests/test_dependency_mgmt.py
  tests/test_dependency_mgmt_version_parsing.py
Labels: enhancement

#551 Refactor dependency repository handling to avoid multiple clones of the same repository
  commodore/component/__init__.py
  commodore/component/compile.py
  commodore/component/template.py
  commodore/config.py
  commodore/dependency_mgmt/__init__.py
  commodore/gitrepo.py
  commodore/multi_dependency.py
  commodore/package/__init__.py
  docs/modules/ROOT/pages/reference/architecture.adoc
  tests/conftest.py
  tests/test_component.py
  tests/test_component_compile.py
  tests/test_config.py
  tests/test_dependency_mgmt.py
  tests/test_dependency_mgmt_jsonnet_bundler.py
  tests/test_gitrepo.py
  tests/test_helpers.py
  tests/test_inventory.py
  tests/test_multi_dependency.py
  tests/test_package.py
  tests/test_package_compile.py
  tests/test_postprocess.py
  tests/test_render_inventory.py
Labels: change

#554 Update `package new` to save the new package in `dependencies/`
  commodore/package/template.py
  tests/test_package_template.py
Labels: ignore

#553 Add command `package update`
  .codeclimate.yml
  commodore/cli.py
  commodore/cruft/__init__.py
  commodore/cruft/__main__.py
  commodore/cruft/_cli.py
  commodore/cruft/_commands/__init__.py
  commodore/cruft/_commands/check.py
  commodore/cruft/_commands/create.py
  commodore/cruft/_commands/diff.py
  commodore/cruft/_commands/link.py
  commodore/cruft/_commands/update.py
  commodore/cruft/_commands/utils/__init__.py
  commodore/cruft/_commands/utils/cookiecutter.py
  commodore/cruft/_commands/utils/cruft.py
  commodore/cruft/_commands/utils/diff.py
  commodore/cruft/_commands/utils/generate.py
  commodore/cruft/_commands/utils/iohelper.py
  commodore/cruft/_logo.py
  commodore/cruft/_version.py
  commodore/cruft/exceptions.py
  commodore/dependency_templater.py
  commodore/package/template.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  poetry.lock
  pyproject.toml
  renovate.json
  tests/conftest.py
  tests/test_cli_functions.py
  tests/test_package_template.py
  tests_cruft/__init__.py
  tests_cruft/conftest.py
  tests_cruft/test_api.py
  tests_cruft/test_cli.py
  tests_cruft/test_exceptions.py
  tests_cruft/test_utils.py
  tests_cruft/testdata/non-unicode-data/.gitattributes
  tests_cruft/testdata/non-unicode-data/data.txt
  tests_cruft/testdata/unicode-data/.gitattributes
  tests_cruft/testdata/unicode-data/data.txt
  tox.ini
Labels: enhancement

#556 Create new components and packages as Git worktree checkouts
  commodore/component/template.py
  commodore/dependency_templater.py
  commodore/gitrepo.py
  commodore/multi_dependency.py
  commodore/package/template.py
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_component_template.py
  tests/test_gitrepo.py
  tests/test_multi_dependency.py
  tests/test_package_template.py
Labels: enhancement

#560 Deduplicate requested test cases for `package new` and `package update`
  commodore/cli.py
  commodore/package/template.py
  docs/modules/ROOT/pages/reference/cli.adoc
  tests/test_package_template.py
Labels: bug

#565 Add flag for providing fallback dynamic facts for `catalog compile`
  commodore/cli.py
  commodore/cluster.py
  commodore/config.py
  docs/modules/ROOT/pages/reference/cli.adoc
  tests/test_catalog_compile.py
  tests/test_cluster.py
  tests/test_config.py
Labels: enhancement

#568 Add logic to try refreshing OIDC token in `login()`
  commodore/config.py
  commodore/login.py
  commodore/tokencache.py
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_config.py
  tests/test_login.py
  tests/test_tokencache.py
Labels: enhancement

#567 Add CLI commands to extract package versions and show rendered inventory
  commodore/cli.py
  commodore/inventory/render.py
  docs/modules/ROOT/pages/reference/cli.adoc
  docs/modules/ROOT/pages/reference/commands.adoc
  tests/test_cli.py
  tests/test_cli_functions.py
Labels: enhancement

#569 Remove reclass warnings from `commodore inventory show` output
  commodore/cli.py
  commodore/inventory/parameters.py
  tests/test_cli_functions.py
Labels: bug
