Repository projectsyn/commodore, pull requests merged in 2023-09, with the labels that each got.

#844 Fetch component and package dependencies in parallel
  commodore/cluster.py
  commodore/dependency_mgmt/__init__.py
  tests/test_target.py
Labels: enhancement

#850 Propagate exceptions raised while fetching dependencies
  commodore/dependency_mgmt/__init__.py
  tests/test_dependency_mgmt.py
Labels: ignore

#848 Use `reclass-rs` in Commodore Docker image
  .github/workflows/build-virtualenv-caches.yml
  .github/workflows/test.yml
  Dockerfile
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
  poetry.lock
  pyproject.toml
  tools/patch-kapitan.sh
  tox.ini
  tox.mk
Labels: enhancement

#852 Fix component ordering in `jsonnetfile.json` and catalog commit message
  commodore/catalog.py
  commodore/dependency_mgmt/jsonnet_bundler.py
Labels: bug

#854 Use multiprocessing start method `spawn` by default
  commodore/cli/__init__.py
Labels: change

#855 Use the projectsyn fork of jsonnet-bundler
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
  tools/install-jb.sh
Labels: enhancement

#858 Bump `jb` to `v0.6.2` in Dockerfile
  Dockerfile
Labels: dependency
