Repository projectsyn/commodore, pull requests merged in 2023-03, with the labels that each got.

#746 Switch to Kapitan's new `literal` multi-line YAML string style
  commodore/helpers.py
Labels: enhancement

#722 Add auto-completion for catalog compilation
  commodore/cli/catalog.py
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
  docs/modules/ROOT/pages/how-to/shell-completion.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
  tests/test_cli_catalog.py
Labels: enhancement

#747 Only print a message when the OIDC login URL can't be opened automatically
  commodore/login.py
Labels: enhancement

#750 Correctly merge instance parameters in `component compile`
  commodore/cluster.py
  commodore/component/compile.py
  tests/test_component_compile.py
Labels: bug

#751 Provide more output for Git errors on push
  commodore/catalog.py
Labels: enhancement

#759 Skip new bandit checks B113, B603, and B607
  tox.ini
Labels: ignore

#757 Add some additional notes for commodore installation
  docs/modules/ROOT/pages/explanation/running-commodore.adoc
Labels: documentation

#762 Add libmagic to system requirements
  README.md
Labels: documentation
